title: Ingeniero Especialista GNU/Linux Sebastián Acuña 
description: "Perfil y documentación de conocimientos de Ingeniero Especialista GNU/Linux Sebastián Acuña"
remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme
show_downloads: True
